version: "3.8"
services:
  server:
    stdin_open: true
    container_name: server
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      - GUNICORN_CMD_ARGS=--reload
    volumes:
      - "./server/:/app"
      - images:/app/images
    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: [ "redis-server", "--port", "6379" ]
  database:
    image: mongo:latest
    container_name: database
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${DBUSERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${DBPASSWORD}
    ports:
      - 27017:27017
    volumes:
      - db_container:/data/db
  worker:
    container_name: worker
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - "./server/:/app"
      - "images:/app/images"
    environment:
      - GUNICORN_CMD_ARGS=--reload
    depends_on:
      - redis
    command: python3 worker.py

volumes:
  db_container:
  images: