version: "3.8"
services:
  server:
    stdin_open: true
    container_name: server
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      - GUNICORN_CMD_ARGS=--reload
    volumes:
      - "./server/:/app"
    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
#  database:
#    stdin_open: true
#    container_name: database
#    build:
#      context: ./database/
#      dockerfile: Dockerfile
#    environment:
#      - GUNICORN_CMD_ARGS=--reload
#    volumes:
#      - "./backend/:/app"
#      # - "/app/"
#    ports:
#      - "5057:5057"